apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-pod-deploy
  labels:
    app: bankapp-pod-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankapp-pod-app
  template:
    metadata:
      labels:
        app: bankapp-pod-app
    spec:
      containers:
      - name: bankapp-pod-container
        image: prashant753/staragile_project1
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-pod-np-service
  labels:
    app: bankapp-pod-app
spec:
  selector:
    app: bankapp-pod-app

  type: NodePort
  ports:
  - nodePort: 31032    
    port: 8082
    targetPort: 8082
